services:
  - type: web
    name: grayleafspotr
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: GRAYLEAFSPOTR_PYTHON
        value: /opt/grayleafspotr-python/bin/python
      - key: GRAYLEAFSPOTR_MODEL_URL
        value: https://huggingface.co/rotsl/grayleafspot-segmentation/resolve/main/best_area_w_0.7.pt
